import Link from "next/link"
import Head from 'next/head'
import Ordering from "../../components/patches/ordering"
import Seo from "../../components/patches/Seo"
import { host2 } from "../../utils/myrconstants"
export const getStaticProps = async (context) => {
  const res = await fetch(`${host2}/api/services`)
    const data =  await res.json()

    const resp = await fetch(`${host2}/api/seo/services`)
    const datas =  await resp.json()
  // console.log("------------------>>>>>>>>>", data.services)
  //  const results = datalooper(data.keywords)
  //  console.log("------------------>>>>>>>>>", results)
    return {
        props: {items: data.services, seo:datas.meta},
        revalidate: 10,
    }
  }
const datalooper = (data)=>{
  let results1 = []
  let results = data.filter(item => {
   let res = servicechecker(item.url)
    if (res){
      results1.push(item)
    }
  })
  return results1
}
const servicechecker = (str) =>{
  const myArray = str.split("/");
  if (myArray[1] === "services"){
    return true
  }else{
    return false
  }

}
const Services = ({items, seo}) => {
    return ( 
        <div>
        <Head >
          {seo && <title>{seo.metaTitle}</title> || <title>Writer </title>}
          {seo && <meta name="description" content={seo.metaDescription} /> || <meta name="description" content="Generated by create next app" /> }
          <link rel="icon" href="/favicon.ico" />
        </Head>
    <div className="my-5 mt-24">
    <div className='lg:mt-0'>
      <h2 className='flex justify-center items-center font-semibold py-10'>Services</h2>
      <div className='max-w-7xl  2xl:mx-auto mx-4 grid lg:grid-cols-3 md:grid-cols-2'>
      {items && items.map(item => (
        <div className=" p-4 shadow-sm" key={item.title}>
          <div className=" p-2 bg-blue-700 text-white"> {item.title}</div>
      {/* <Link href={item.url}><a className="cursor-pointer"> <div className=" p-2 bg-blue-700 text-white"> {item.title}</div></a></Link> */}
        {item.children && item.children.map(child => (
        <div className="p-2 cursor-pointer" key={child.id.url}>
            <Link href={'/services/'+child.id.url}><a className="cursor-pointer">{child.id.name}</a></Link>
            </div>
      ))}
        </div>
      ))}
      </div>
      </div>
    </div>
    { seo && <Seo body={seo.footerContent}/> || <Seo heading={"Service seo"} body={"service body"}/>} 
        <div className='-mb-5'><Ordering /></div>
  </div>
     );
}
 
export default Services;