import Head from 'next/head'
import {host2} from "../../utils/myrconstants"

export const getStaticProps = async ({params}) => {
    const res = await fetch(`${host2}/api/maswali/` + params.url)
     const data =  await res.json()

     console.log("--------------", data)
    if (Object.keys(data).length === 0) {
      return {
        notFound: true,
        props: {},
        revalidate: 10,
      };
    }
    return {
        props: {maswali: data.maswali},
        revalidate: 10,
    }
}
export const getStaticPaths = async() => {
    let data = await fetch(`${host2}/api/maswali/getall`)
    data = await data.json();
    let paths = [];
    data.maswali?.forEach((d) => {
      paths.push({
        params: {
            url: d?.url,
        },
      });
    });
  
    return {
      paths,
      fallback: true,
    };
  }
const Question = (maswali) => {
    // const [question, setQuestion] = useState({id: 1, name: "question 1", url: "question-1", description: "the description of question 1"})
    return ( 
        <>
        {maswali && <>
        <Head >
          {maswali && <title>{maswali.title}</title> || <title>Writer </title>}
          {maswali && <meta name="description" content={maswali.meta} /> || <meta name="description" content="Generated by create next app" /> }
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="mt-32  max-w-7xl mx-6  2xl:mx-auto ">
            <h1 className="py-3 text-xl text-blue-700">{maswali.topic}</h1>
           <div className="peer text-lg py-4" dangerouslySetInnerHTML={{__html: maswali.question}}></div>
           <div className="  flex justify-start items-start h-32 my-5 pb-10">
            <div className="bgimging h-48 w-96 mb-10 ">
           <div className="bgon flex justify-center items-start text-2xl text-blue-700 font-semiboold py-5"><div classNamecle="avas"> ${maswali.cost} -Buy a ready Answer.</div></div>
            <br />
            <div className="flex justify-center items-startexo text-lg"><a href="https://acemywriter.com/order"><span className="cursor-pointer bg-blue-700 text-white p-2 rounded-md">Order your 0% plagiarized answer</span></a></div>
            </div>
           </div>
        </div></>}
        </>
     );
}
 
export default Question;