import Hero1 from "../../components/heros/hero1";
import Ordering from "../../components/patches/ordering";
import {host} from "../../utils/myrconstants"
import Head from 'next/head'

export const getStaticProps = async ({params}) => {
    const res = await fetch(`${host}/api/blog/` + params.url)
     const data =  await res.json()

    //  console.log("--------------", data)
    if (Object.keys(data).length === 0) {
      return {
        notFound: true,
        props: {},
        revalidate: 10,
      };
    }
    return {
        props: {blog: data.article},
        revalidate: 10,
    }
}
export const getStaticPaths = async() => {
    let blogs = await fetch(`${host}/api/blog`)
    blogs = await blogs.json();
    let paths = [];
    blogs.articles?.forEach((blog) => {
      paths.push({
        params: {
            url: blog?.url,
        },
      });
    });
  
    return {
      paths,
      fallback: true,
    };
  }
const Blog = ({blog}) => {
    // console.log("--------------", blog)
    return ( 
        <>
        <Head >
          {blog && <title>{blog.metaTitle}</title> || <title>Writer </title>}
          {blog && <meta name="description" content={blog.metaDescription} /> || <meta name="description" content="Generated by create next app" /> }
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="">
            <Hero1 heading={blog.h1}  meta={blog.meta} capture={blog.capture} image={blog.image} title={blog.title}/>
            <div className="max-w-7xl xl:mx-auto mx-6 peer py-4">
           <div className="text-base mt-8 blogi" dangerouslySetInnerHTML={{__html: blog.body}}>
         </div>
            </div>
        </div>
        <div className='-mb-5'><Ordering /></div>
        </>
     );
}
 
export default Blog;